/* Generated by scripts/capture-scenes.mjs — do not edit by hand. */
// prettier-ignore
export const scenes = {
  "platform": {
    "src": "/product-3d/scenes/platform.webp",
    "src800": "/product-3d/scenes/platform-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Digital Experience Platform",
    "tagline": "One Platform. Every Industry. Every Estate."
  },
  "inventory": {
    "src": "/product-3d/scenes/inventory.webp",
    "src800": "/product-3d/scenes/inventory-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Unified Cloud Inventory",
    "tagline": "One inventory. Every cloud. Full control."
  },
  "cloud-connectors": {
    "src": "/product-3d/scenes/cloud-connectors.webp",
    "src800": "/product-3d/scenes/cloud-connectors-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Cloud Connectors",
    "tagline": "Connect once. Govern everywhere."
  },
  "identity": {
    "src": "/product-3d/scenes/identity.webp",
    "src800": "/product-3d/scenes/identity-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Identity & Access",
    "tagline": "One identity fabric. Every estate."
  },
  "provisioning": {
    "src": "/product-3d/scenes/provisioning.webp",
    "src800": "/product-3d/scenes/provisioning-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Service Catalog",
    "tagline": "Approved resources. No consoles."
  },
  "itsm": {
    "src": "/product-3d/scenes/itsm.webp",
    "src800": "/product-3d/scenes/itsm-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "ITSM",
    "tagline": "Service management, cloud-ops native."
  },
  "observe": {
    "src": "/product-3d/scenes/observe.webp",
    "src800": "/product-3d/scenes/observe-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Observe",
    "tagline": "Logs, metrics, traces, SLOs — included."
  },
  "whalenomics": {
    "src": "/product-3d/scenes/whalenomics.webp",
    "src800": "/product-3d/scenes/whalenomics-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Whalenomics · FinOps",
    "tagline": "Every dollar resolves to a workload and an owner."
  },
  "migration": {
    "src": "/product-3d/scenes/migration.webp",
    "src800": "/product-3d/scenes/migration-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Migration Engine",
    "tagline": "Entry, movement and exit — scored and rehearsed."
  },
  "whaleforge": {
    "src": "/product-3d/scenes/whaleforge.webp",
    "src800": "/product-3d/scenes/whaleforge-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "WhaleForge IaC",
    "tagline": "YAML in. Terraform and diagrams out."
  },
  "landing-zone": {
    "src": "/product-3d/scenes/landing-zone.webp",
    "src800": "/product-3d/scenes/landing-zone-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Landing Zone Builder",
    "tagline": "Compliant foundations, designed visually."
  },
  "cloud-audit": {
    "src": "/product-3d/scenes/cloud-audit.webp",
    "src800": "/product-3d/scenes/cloud-audit-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Cloud Audit & Evidence",
    "tagline": "Controls monitored continuously. Evidence on demand."
  },
  "whale-ai": {
    "src": "/product-3d/scenes/whale-ai.webp",
    "src800": "/product-3d/scenes/whale-ai-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Whale AI — including offline",
    "tagline": "AI in every family. Inside the perimeter."
  },
  "tenancy": {
    "src": "/product-3d/scenes/tenancy.webp",
    "src800": "/product-3d/scenes/tenancy-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Tenancy & Monetization",
    "tagline": "Revenue per tenant, on capacity you own."
  },
  "sovereign-operations": {
    "src": "/product-3d/scenes/sovereign-operations.webp",
    "src800": "/product-3d/scenes/sovereign-operations-800.webp",
    "width": 1908,
    "height": 1032,
    "title": "Sovereign Operations",
    "tagline": "Sovereignty as a property of the architecture."
  },
  "industry-government": {
    "src": "/product-3d/scenes/industry-government.webp",
    "src800": "/product-3d/scenes/industry-government-800.webp",
    "width": 1908,
    "height": 1032,
    "title": "Government",
    "tagline": "Sovereign operations, air-gapped when required."
  },
  "industry-bfsi": {
    "src": "/product-3d/scenes/industry-bfsi.webp",
    "src800": "/product-3d/scenes/industry-bfsi-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "BFSI",
    "tagline": "Answer an inspection from a system of record."
  },
  "industry-healthcare": {
    "src": "/product-3d/scenes/industry-healthcare.webp",
    "src800": "/product-3d/scenes/industry-healthcare-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Healthcare",
    "tagline": "Clinical systems governed in-country."
  },
  "industry-regulated-enterprise": {
    "src": "/product-3d/scenes/industry-regulated-enterprise.webp",
    "src800": "/product-3d/scenes/industry-regulated-enterprise-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Regulated Enterprise",
    "tagline": "Six clouds and the datacenter floor, one estate."
  },
  "industry-saas": {
    "src": "/product-3d/scenes/industry-saas.webp",
    "src800": "/product-3d/scenes/industry-saas-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "SaaS & Digital Native",
    "tagline": "Governed from the first account."
  },
  "industry-telco": {
    "src": "/product-3d/scenes/industry-telco.webp",
    "src800": "/product-3d/scenes/industry-telco-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Telco & MSP",
    "tagline": "Operators become cloud providers."
  },
  "industry-datacenter": {
    "src": "/product-3d/scenes/industry-datacenter.webp",
    "src800": "/product-3d/scenes/industry-datacenter-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Datacenter & Colocation",
    "tagline": "Rent per megawatt becomes revenue per tenant."
  },
  "fabric": {
    "src": "/product-3d/scenes/fabric.webp",
    "src800": "/product-3d/scenes/fabric-800.webp",
    "width": 1908,
    "height": 1033,
    "title": "BlueWhale Stack Fabric",
    "tagline": "Every datacenter. One fabric."
  },
  "architecture": {
    "src": "/product-3d/scenes/architecture.webp",
    "src800": "/product-3d/scenes/architecture-800.webp",
    "width": 1707,
    "height": 952,
    "title": "The architecture, top to bottom",
    "tagline": "Six layers. One platform build."
  },
  "edition-standard": {
    "src": "/product-3d/scenes/edition-standard.webp",
    "src800": "/product-3d/scenes/edition-standard-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Standard Edition",
    "tagline": "Governed cloud for a single estate."
  },
  "edition-enterprise": {
    "src": "/product-3d/scenes/edition-enterprise.webp",
    "src800": "/product-3d/scenes/edition-enterprise-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Enterprise Edition",
    "tagline": "Every estate answerable from one console."
  },
  "edition-telco-datacenter": {
    "src": "/product-3d/scenes/edition-telco-datacenter.webp",
    "src800": "/product-3d/scenes/edition-telco-datacenter-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Telco & Datacenter Edition",
    "tagline": "Operators become cloud providers."
  },
  "edition-government": {
    "src": "/product-3d/scenes/edition-government.webp",
    "src800": "/product-3d/scenes/edition-government-800.webp",
    "width": 1908,
    "height": 1032,
    "title": "Government Edition",
    "tagline": "Sovereignty demonstrated by the architecture."
  },
  "solution-unified-cloud-inventory": {
    "src": "/product-3d/scenes/solution-unified-cloud-inventory.webp",
    "src800": "/product-3d/scenes/solution-unified-cloud-inventory-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Unified Cloud Inventory",
    "tagline": "Six clouds and on-prem, one live map."
  },
  "solution-ai-native-provisioning": {
    "src": "/product-3d/scenes/solution-ai-native-provisioning.webp",
    "src800": "/product-3d/scenes/solution-ai-native-provisioning-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "AI-Native Provisioning",
    "tagline": "Approved resources, right-sized, no consoles."
  },
  "solution-bundled-observability": {
    "src": "/product-3d/scenes/solution-bundled-observability.webp",
    "src800": "/product-3d/scenes/solution-bundled-observability-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Bundled Observability",
    "tagline": "Logs, metrics, traces and SLOs — in the licence."
  },
  "solution-cloud-migration": {
    "src": "/product-3d/scenes/solution-cloud-migration.webp",
    "src800": "/product-3d/scenes/solution-cloud-migration-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Cloud Migration",
    "tagline": "Scored, sequenced, rehearsed."
  },
  "solution-security-compliance": {
    "src": "/product-3d/scenes/solution-security-compliance.webp",
    "src800": "/product-3d/scenes/solution-security-compliance-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Security & Compliance",
    "tagline": "One identity fabric. One audit trail."
  },
  "solution-sovereign-cloud": {
    "src": "/product-3d/scenes/solution-sovereign-cloud.webp",
    "src800": "/product-3d/scenes/solution-sovereign-cloud-800.webp",
    "width": 1908,
    "height": 1032,
    "title": "Sovereign Cloud",
    "tagline": "In-country. Air-gapped. In-region AI."
  },
  "estate": {
    "src": "/product-3d/scenes/estate.webp",
    "src800": "/product-3d/scenes/estate-800.webp",
    "width": 1908,
    "height": 1034,
    "title": "Every estate, one control plane",
    "tagline": "Every cloud. One control plane."
  }
} as const;

export type SceneKey = keyof typeof scenes;
