/* Generated by scripts/render-scene.mjs — do not edit by hand. */
// prettier-ignore
export const scenes = {
  "platform": {
    "src": "/product-3d/scenes/platform.webp",
    "src800": "/product-3d/scenes/platform-800.webp",
    "width": 1997,
    "height": 814,
    "title": "Digital Experience Platform",
    "tagline": "One Platform. Every Industry. Every Estate.",
    "cableTargets": [
      [
        0.2521,
        0.0061
      ],
      [
        0.3274,
        0.0061
      ],
      [
        0.4026,
        0.0061
      ],
      [
        0.4952,
        0.0061
      ],
      [
        0.5879,
        0.0061
      ],
      [
        0.6631,
        0.0061
      ],
      [
        0.7384,
        0.0061
      ]
    ],
    "groups": [
      {
        "label": "Public cloud",
        "at": [
          0.2845,
          0.5668
        ]
      },
      {
        "label": "Private & virtual",
        "at": [
          0.4952,
          0.5668
        ]
      },
      {
        "label": "Hybrid & edge",
        "at": [
          0.706,
          0.5668
        ]
      }
    ],
    "tag": [
      0.4952,
      0.979
    ],
    "panelTop": [
      0.4952,
      0.0061
    ]
  },
  "inventory": {
    "src": "/product-3d/scenes/inventory.webp",
    "src800": "/product-3d/scenes/inventory-800.webp",
    "width": 1997,
    "height": 814,
    "title": "Unified Cloud Inventory",
    "tagline": "One inventory. Every cloud. Full control.",
    "cableTargets": [
      [
        0.2521,
        0.0061
      ],
      [
        0.3274,
        0.0061
      ],
      [
        0.4026,
        0.0061
      ],
      [
        0.4952,
        0.0061
      ],
      [
        0.5879,
        0.0061
      ],
      [
        0.6631,
        0.0061
      ],
      [
        0.7384,
        0.0061
      ]
    ],
    "groups": [
      {
        "label": "Compute",
        "at": [
          0.2845,
          0.5668
        ]
      },
      {
        "label": "Databases",
        "at": [
          0.4952,
          0.5668
        ]
      },
      {
        "label": "Storage",
        "at": [
          0.706,
          0.5668
        ]
      }
    ],
    "tag": [
      0.4952,
      0.979
    ],
    "panelTop": [
      0.4952,
      0.0061
    ]
  },
  "cloud-connectors": {
    "src": "/product-3d/scenes/cloud-connectors.webp",
    "src800": "/product-3d/scenes/cloud-connectors-800.webp",
    "width": 1997,
    "height": 814,
    "title": "Cloud Connectors",
    "tagline": "Connect once. Govern everywhere.",
    "cableTargets": [
      [
        0.2521,
        0.0061
      ],
      [
        0.3274,
        0.0061
      ],
      [
        0.4026,
        0.0061
      ],
      [
        0.4952,
        0.0061
      ],
      [
        0.5879,
        0.0061
      ],
      [
        0.6631,
        0.0061
      ],
      [
        0.7384,
        0.0061
      ]
    ],
    "groups": [
      {
        "label": "Public cloud",
        "at": [
          0.2845,
          0.5668
        ]
      },
      {
        "label": "Private & virtual",
        "at": [
          0.4952,
          0.5668
        ]
      },
      {
        "label": "Edge Agent",
        "at": [
          0.706,
          0.5668
        ]
      }
    ],
    "tag": [
      0.4952,
      0.979
    ],
    "panelTop": [
      0.4952,
      0.0061
    ]
  },
  "identity": {
    "src": "/product-3d/scenes/identity.webp",
    "src800": "/product-3d/scenes/identity-800.webp",
    "width": 1997,
    "height": 814,
    "title": "Identity & Access",
    "tagline": "One identity fabric. Every estate.",
    "cableTargets": [
      [
        0.2521,
        0.0061
      ],
      [
        0.3274,
        0.0061
      ],
      [
        0.4026,
        0.0061
      ],
      [
        0.4952,
        0.0061
      ],
      [
        0.5879,
        0.0061
      ],
      [
        0.6631,
        0.0061
      ],
      [
        0.7384,
        0.0061
      ]
    ],
    "groups": [
      {
        "label": "Providers",
        "at": [
          0.2845,
          0.5668
        ]
      },
      {
        "label": "Roles",
        "at": [
          0.4952,
          0.5668
        ]
      },
      {
        "label": "Access",
        "at": [
          0.706,
          0.5668
        ]
      }
    ],
    "tag": [
      0.4952,
      0.979
    ],
    "panelTop": [
      0.4952,
      0.0061
    ]
  },
  "provisioning": {
    "src": "/product-3d/scenes/provisioning.webp",
    "src800": "/product-3d/scenes/provisioning-800.webp",
    "width": 1997,
    "height": 814,
    "title": "Service Catalog",
    "tagline": "Approved resources. No consoles.",
    "cableTargets": [
      [
        0.2521,
        0.0061
      ],
      [
        0.3274,
        0.0061
      ],
      [
        0.4026,
        0.0061
      ],
      [
        0.4952,
        0.0061
      ],
      [
        0.5879,
        0.0061
      ],
      [
        0.6631,
        0.0061
      ],
      [
        0.7384,
        0.0061
      ]
    ],
    "groups": [
      {
        "label": "Catalog",
        "at": [
          0.2845,
          0.5668
        ]
      },
      {
        "label": "Approvals",
        "at": [
          0.4952,
          0.5668
        ]
      },
      {
        "label": "Deployed",
        "at": [
          0.706,
          0.5668
        ]
      }
    ],
    "tag": [
      0.4952,
      0.979
    ],
    "panelTop": [
      0.4952,
      0.0061
    ]
  },
  "itsm": {
    "src": "/product-3d/scenes/itsm.webp",
    "src800": "/product-3d/scenes/itsm-800.webp",
    "width": 1997,
    "height": 814,
    "title": "ITSM",
    "tagline": "Service management, cloud-ops native.",
    "cableTargets": [
      [
        0.2521,
        0.0061
      ],
      [
        0.3274,
        0.0061
      ],
      [
        0.4026,
        0.0061
      ],
      [
        0.4952,
        0.0061
      ],
      [
        0.5879,
        0.0061
      ],
      [
        0.6631,
        0.0061
      ],
      [
        0.7384,
        0.0061
      ]
    ],
    "groups": [
      {
        "label": "Incidents",
        "at": [
          0.2845,
          0.5668
        ]
      },
      {
        "label": "Changes",
        "at": [
          0.4952,
          0.5668
        ]
      },
      {
        "label": "CMDB",
        "at": [
          0.706,
          0.5668
        ]
      }
    ],
    "tag": [
      0.4952,
      0.979
    ],
    "panelTop": [
      0.4952,
      0.0061
    ]
  },
  "observe": {
    "src": "/product-3d/scenes/observe.webp",
    "src800": "/product-3d/scenes/observe-800.webp",
    "width": 1997,
    "height": 814,
    "title": "Observe",
    "tagline": "Logs, metrics, traces, SLOs — bundled.",
    "cableTargets": [
      [
        0.2521,
        0.0061
      ],
      [
        0.3274,
        0.0061
      ],
      [
        0.4026,
        0.0061
      ],
      [
        0.4952,
        0.0061
      ],
      [
        0.5879,
        0.0061
      ],
      [
        0.6631,
        0.0061
      ],
      [
        0.7384,
        0.0061
      ]
    ],
    "groups": [
      {
        "label": "Logs",
        "at": [
          0.2845,
          0.5668
        ]
      },
      {
        "label": "Metrics & traces",
        "at": [
          0.4952,
          0.5668
        ]
      },
      {
        "label": "SLOs",
        "at": [
          0.706,
          0.5668
        ]
      }
    ],
    "tag": [
      0.4952,
      0.979
    ],
    "panelTop": [
      0.4952,
      0.0061
    ]
  },
  "whalenomics": {
    "src": "/product-3d/scenes/whalenomics.webp",
    "src800": "/product-3d/scenes/whalenomics-800.webp",
    "width": 1997,
    "height": 814,
    "title": "Whalenomics · FinOps",
    "tagline": "Spend explained. Decomposed. Owned.",
    "cableTargets": [
      [
        0.2521,
        0.0061
      ],
      [
        0.3274,
        0.0061
      ],
      [
        0.4026,
        0.0061
      ],
      [
        0.4952,
        0.0061
      ],
      [
        0.5879,
        0.0061
      ],
      [
        0.6631,
        0.0061
      ],
      [
        0.7384,
        0.0061
      ]
    ],
    "groups": [
      {
        "label": "Budgets",
        "at": [
          0.2845,
          0.5668
        ]
      },
      {
        "label": "Chargeback",
        "at": [
          0.4952,
          0.5668
        ]
      },
      {
        "label": "Optimization",
        "at": [
          0.706,
          0.5668
        ]
      }
    ],
    "tag": [
      0.4952,
      0.979
    ],
    "panelTop": [
      0.4952,
      0.0061
    ]
  },
  "migration": {
    "src": "/product-3d/scenes/migration.webp",
    "src800": "/product-3d/scenes/migration-800.webp",
    "width": 1997,
    "height": 814,
    "title": "Migration Engine",
    "tagline": "Entry, movement and exit — industrialized.",
    "cableTargets": [
      [
        0.2521,
        0.0061
      ],
      [
        0.3274,
        0.0061
      ],
      [
        0.4026,
        0.0061
      ],
      [
        0.4952,
        0.0061
      ],
      [
        0.5879,
        0.0061
      ],
      [
        0.6631,
        0.0061
      ],
      [
        0.7384,
        0.0061
      ]
    ],
    "groups": [
      {
        "label": "Discover",
        "at": [
          0.2845,
          0.5668
        ]
      },
      {
        "label": "6R assess",
        "at": [
          0.4952,
          0.5668
        ]
      },
      {
        "label": "Waves",
        "at": [
          0.706,
          0.5668
        ]
      }
    ],
    "tag": [
      0.4952,
      0.979
    ],
    "panelTop": [
      0.4952,
      0.0061
    ]
  },
  "whaleforge": {
    "src": "/product-3d/scenes/whaleforge.webp",
    "src800": "/product-3d/scenes/whaleforge-800.webp",
    "width": 1997,
    "height": 814,
    "title": "WhaleForge IaC",
    "tagline": "YAML in. Terraform and diagrams out.",
    "cableTargets": [
      [
        0.2521,
        0.0061
      ],
      [
        0.3274,
        0.0061
      ],
      [
        0.4026,
        0.0061
      ],
      [
        0.4952,
        0.0061
      ],
      [
        0.5879,
        0.0061
      ],
      [
        0.6631,
        0.0061
      ],
      [
        0.7384,
        0.0061
      ]
    ],
    "groups": [
      {
        "label": "YAML",
        "at": [
          0.2845,
          0.5668
        ]
      },
      {
        "label": "Terraform",
        "at": [
          0.4952,
          0.5668
        ]
      },
      {
        "label": "Diagrams",
        "at": [
          0.706,
          0.5668
        ]
      }
    ],
    "tag": [
      0.4952,
      0.979
    ],
    "panelTop": [
      0.4952,
      0.0061
    ]
  },
  "landing-zone": {
    "src": "/product-3d/scenes/landing-zone.webp",
    "src800": "/product-3d/scenes/landing-zone-800.webp",
    "width": 1997,
    "height": 814,
    "title": "Landing Zone Builder",
    "tagline": "Compliant foundations, designed visually.",
    "cableTargets": [
      [
        0.2521,
        0.0061
      ],
      [
        0.3274,
        0.0061
      ],
      [
        0.4026,
        0.0061
      ],
      [
        0.4952,
        0.0061
      ],
      [
        0.5879,
        0.0061
      ],
      [
        0.6631,
        0.0061
      ],
      [
        0.7384,
        0.0061
      ]
    ],
    "groups": [
      {
        "label": "Accounts",
        "at": [
          0.2845,
          0.5668
        ]
      },
      {
        "label": "Guardrails",
        "at": [
          0.4952,
          0.5668
        ]
      },
      {
        "label": "Baseline",
        "at": [
          0.706,
          0.5668
        ]
      }
    ],
    "tag": [
      0.4952,
      0.979
    ],
    "panelTop": [
      0.4952,
      0.0061
    ]
  },
  "cloud-audit": {
    "src": "/product-3d/scenes/cloud-audit.webp",
    "src800": "/product-3d/scenes/cloud-audit-800.webp",
    "width": 1997,
    "height": 814,
    "title": "Cloud Audit & Evidence",
    "tagline": "Controls monitored continuously. Evidence on demand.",
    "cableTargets": [
      [
        0.2521,
        0.0061
      ],
      [
        0.3274,
        0.0061
      ],
      [
        0.4026,
        0.0061
      ],
      [
        0.4952,
        0.0061
      ],
      [
        0.5879,
        0.0061
      ],
      [
        0.6631,
        0.0061
      ],
      [
        0.7384,
        0.0061
      ]
    ],
    "groups": [
      {
        "label": "Policies",
        "at": [
          0.2845,
          0.5668
        ]
      },
      {
        "label": "Controls",
        "at": [
          0.4952,
          0.5668
        ]
      },
      {
        "label": "Evidence",
        "at": [
          0.706,
          0.5668
        ]
      }
    ],
    "tag": [
      0.4952,
      0.979
    ],
    "panelTop": [
      0.4952,
      0.0061
    ]
  },
  "whale-ai": {
    "src": "/product-3d/scenes/whale-ai.webp",
    "src800": "/product-3d/scenes/whale-ai-800.webp",
    "width": 1997,
    "height": 814,
    "title": "Whale AI — including offline",
    "tagline": "AI in every family. Inside the perimeter.",
    "cableTargets": [
      [
        0.2521,
        0.0061
      ],
      [
        0.3274,
        0.0061
      ],
      [
        0.4026,
        0.0061
      ],
      [
        0.4952,
        0.0061
      ],
      [
        0.5879,
        0.0061
      ],
      [
        0.6631,
        0.0061
      ],
      [
        0.7384,
        0.0061
      ]
    ],
    "groups": [
      {
        "label": "Operations",
        "at": [
          0.2845,
          0.5668
        ]
      },
      {
        "label": "Documentation",
        "at": [
          0.4952,
          0.5668
        ]
      },
      {
        "label": "Compliance",
        "at": [
          0.706,
          0.5668
        ]
      }
    ],
    "tag": [
      0.4952,
      0.979
    ],
    "panelTop": [
      0.4952,
      0.0061
    ]
  },
  "tenancy": {
    "src": "/product-3d/scenes/tenancy.webp",
    "src800": "/product-3d/scenes/tenancy-800.webp",
    "width": 1997,
    "height": 814,
    "title": "Tenancy & Monetization",
    "tagline": "Revenue per tenant, on capacity you own.",
    "cableTargets": [
      [
        0.2521,
        0.0061
      ],
      [
        0.3274,
        0.0061
      ],
      [
        0.4026,
        0.0061
      ],
      [
        0.4952,
        0.0061
      ],
      [
        0.5879,
        0.0061
      ],
      [
        0.6631,
        0.0061
      ],
      [
        0.7384,
        0.0061
      ]
    ],
    "groups": [
      {
        "label": "Tenants",
        "at": [
          0.2845,
          0.5668
        ]
      },
      {
        "label": "Marketplace",
        "at": [
          0.4952,
          0.5668
        ]
      },
      {
        "label": "Metering",
        "at": [
          0.706,
          0.5668
        ]
      }
    ],
    "tag": [
      0.4952,
      0.979
    ],
    "panelTop": [
      0.4952,
      0.0061
    ]
  },
  "sovereign-operations": {
    "src": "/product-3d/scenes/sovereign-operations.webp",
    "src800": "/product-3d/scenes/sovereign-operations-800.webp",
    "width": 1997,
    "height": 814,
    "title": "Sovereign Operations",
    "tagline": "Sovereignty demonstrated, not asserted.",
    "cableTargets": [
      [
        0.2521,
        0.0061
      ],
      [
        0.3274,
        0.0061
      ],
      [
        0.4026,
        0.0061
      ],
      [
        0.4952,
        0.0061
      ],
      [
        0.5879,
        0.0061
      ],
      [
        0.6631,
        0.0061
      ],
      [
        0.7384,
        0.0061
      ]
    ],
    "groups": [
      {
        "label": "Zones",
        "at": [
          0.2845,
          0.5668
        ]
      },
      {
        "label": "Directorates",
        "at": [
          0.4952,
          0.5668
        ]
      },
      {
        "label": "Edge sites",
        "at": [
          0.706,
          0.5668
        ]
      }
    ],
    "tag": [
      0.4952,
      0.979
    ],
    "panelTop": [
      0.4952,
      0.0061
    ]
  }
} as const;

export type SceneKey = keyof typeof scenes;
