import {
  type LucideProps,
  HelpCircle,
  // foundation / platform
  KeyRound,
  Cloud,
  Boxes,
  PackagePlus,
  ScrollText,
  Headset,
  Activity,
  MoveRight,
  ShieldCheck,
  LayoutTemplate,
  Wallet,
  Server,
  HardDrive,
  Gauge,
  DatabaseBackup,
  Sparkles,
  // industries
  Landmark,
  RadioTower,
  Banknote,
  HeartPulse,
  Factory,
  Zap,
  Clapperboard,
  Building2,
  Rocket,
  // home / misc
  Workflow,
  Network,
  TrendingUp,
  TrendingDown,
  ShieldAlert,
  Eye,
  // partners
  Plug,
  Handshake,
  FileCheck,
  ReceiptText,
  Users,
  Percent,
  CreditCard,
  Layers,
  GraduationCap,
  Mail,
  ArrowRight,
  ArrowUpRight,
  // trust center
  Globe,
  Lock,
  UserCheck,
  FileLock2,
  RefreshCw,
  Star,
  FileText,
} from "lucide-react";

/**
 * Explicit icon registry — only the icons actually referenced in content are
 * imported, so client bundles stay small (a namespace `import * as Lucide`
 * would pull the entire library into the client bundle).
 */
const REGISTRY: Record<string, React.ComponentType<LucideProps>> = {
  KeyRound,
  Cloud,
  Boxes,
  PackagePlus,
  ScrollText,
  Headset,
  Activity,
  MoveRight,
  ShieldCheck,
  LayoutTemplate,
  Wallet,
  Server,
  HardDrive,
  Gauge,
  DatabaseBackup,
  Sparkles,
  Landmark,
  RadioTower,
  Banknote,
  HeartPulse,
  Factory,
  Zap,
  Clapperboard,
  Building2,
  Rocket,
  Workflow,
  Network,
  TrendingUp,
  TrendingDown,
  ShieldAlert,
  Eye,
  Plug,
  Handshake,
  FileCheck,
  ReceiptText,
  Users,
  Percent,
  CreditCard,
  Layers,
  GraduationCap,
  Mail,
  ArrowRight,
  ArrowUpRight,
  Globe,
  Lock,
  UserCheck,
  FileLock2,
  RefreshCw,
  Star,
  FileText,
};

/** Render a content-driven icon by name; falls back to HelpCircle. */
export function Icon({ name, ...props }: { name: string } & LucideProps) {
  const Cmp = REGISTRY[name] ?? HelpCircle;
  return <Cmp {...props} />;
}
