// Captures the static (transparent WebP) version of every live product scene
// from the running site (/scene-capture) and writes content/scenes.generated.ts.
// Usage: node scripts/capture-scenes.mjs [base=http://localhost:3100] [key,key,...|all]
import puppeteer from "puppeteer-core";
import sharp from "sharp";
import fs from "node:fs";

const base = process.argv[2] || "http://localhost:3100";
const arg = process.argv[3];
const registry = fs.readFileSync("components/scenes/live/registry.ts", "utf8");
// scene keys are the object keys at exactly two-space indent inside SCENES (skip the interface above it)
const scenesSrc = registry.slice(registry.indexOf("export const SCENES"));
const ALL = [...scenesSrc.matchAll(/^ {2}"?([a-z0-9-]+)"?: \{/gm)].map((m) => m[1]);
const keys = arg && arg !== "all" ? arg.split(",") : [...new Set(ALL)];
const outDir = "public/product-3d/scenes";
fs.mkdirSync(outDir, { recursive: true });
const genPath = "content/scenes.generated.ts";
const existing = fs.existsSync(genPath) ? readExisting() : {};
function readExisting() {
  try { const m = fs.readFileSync(genPath, "utf8").match(/= (\{[\s\S]*\}) as const;/); return m ? JSON.parse(m[1]) : {}; } catch { return {}; }
}
// titles/taglines come from the registry
const defs = {};
for (const m of scenesSrc.matchAll(/^ {2}"?([a-z0-9-]+)"?: \{[\s\S]*?title: "([^"]+)",\s*tagline: "([^"]+)"/gm)) defs[m[1]] = { title: m[2], tagline: m[3] };

const W = 2000, H = 1125;
const browser = await puppeteer.launch({
  executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe",
  headless: true,
  args: ["--no-sandbox", "--hide-scrollbars", "--use-gl=angle", "--use-angle=swiftshader", "--enable-unsafe-swiftshader", "--ignore-gpu-blocklist"],
});
const page = await browser.newPage();
await page.setViewport({ width: W, height: H, deviceScaleFactor: 1 });
page.on("pageerror", (e) => console.log("  page error:", e.message));

for (const key of keys) {
  const t0 = Date.now();
  await page.goto(`${base}/scene-capture?key=${key}&w=${W}&h=${H}&angle=0`, { waitUntil: "load", timeout: 180_000 });
  try {
    await page.waitForFunction(() => window.__sceneReady === true, { timeout: 90_000 });
  } catch {
    console.log(`${key.padEnd(34)} SKIPPED — scene never signalled ready (unknown key or render error)`);
    continue;
  }
  await new Promise((r) => setTimeout(r, 400));
  const canvas = await page.$("canvas");
  const png = await canvas.screenshot({ type: "png", omitBackground: true });
  const trimmed = await sharp(png).trim({ threshold: 8 }).png().toBuffer({ resolveWithObject: true });
  const { width, height, trimOffsetLeft = 0, trimOffsetTop = 0 } = trimmed.info;
  const file = `${outDir}/${key}.webp`;
  await sharp(trimmed.data).webp({ quality: 86, alphaQuality: 90, effort: 5 }).toFile(file);
  const small = `${outDir}/${key}-800.webp`;
  await sharp(trimmed.data).resize({ width: 800 }).webp({ quality: 82, alphaQuality: 90 }).toFile(small);
  const d = defs[key] ?? { title: key, tagline: "" };
  existing[key] = { src: `/${file.replace(/^public\//, "")}`, src800: `/${small.replace(/^public\//, "")}`, width, height, title: d.title, tagline: d.tagline };
  console.log(`${key.padEnd(34)} ${width}x${height} @${-trimOffsetLeft},${-trimOffsetTop}  ${Math.round(fs.statSync(file).size / 1024)}KB  (${((Date.now() - t0) / 1000).toFixed(1)}s)`);
}
await browser.close();

// drop scenes that no longer exist in the registry
for (const k of Object.keys(existing)) if (!defs[k]) delete existing[k];
const body = JSON.stringify(existing, null, 2);
fs.writeFileSync(genPath, `/* Generated by scripts/capture-scenes.mjs — do not edit by hand. */\n// prettier-ignore\nexport const scenes = ${body} as const;\n\nexport type SceneKey = keyof typeof scenes;\n`);
console.log(`wrote ${genPath} (${Object.keys(existing).length} scenes)`);
