// Renders the object-only (transparent) 3D product scenes used natively on the
// website by components/scenes/ProductScene.tsx, and writes their label
// anchors to content/scenes.generated.ts.
// Usage: node scripts/render-scene.mjs [scene,scene,...|all]
import puppeteer from "puppeteer-core";
import sharp from "sharp";
import path from "node:path";
import fs from "node:fs";
import { pathToFileURL } from "node:url";

const ALL = [
  "platform", "inventory", "cloud-connectors", "identity", "provisioning", "itsm", "observe",
  "whalenomics", "migration", "whaleforge", "landing-zone", "cloud-audit", "whale-ai", "tenancy",
  "sovereign-operations",
  "industry-government", "industry-bfsi", "industry-healthcare", "industry-regulated-enterprise",
  "industry-saas", "industry-telco", "industry-datacenter", "fabric",
];
const arg = process.argv[2];
const scenes = arg && arg !== "all" ? arg.split(",") : ALL;
const outDir = "public/product-3d/scenes";
fs.mkdirSync(outDir, { recursive: true });
const html = pathToFileURL(path.resolve("scripts/render-3d/infographic.html")).href;

const genPath = "content/scenes.generated.ts";
const existing = fs.existsSync(genPath) ? readExisting() : {};
function readExisting() {
  try { const m = fs.readFileSync(genPath, "utf8").match(/= (\{[\s\S]*\}) as const;/); return m ? JSON.parse(m[1]) : {}; } catch { return {}; }
}

const browser = await puppeteer.launch({
  executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe",
  headless: true,
  args: ["--no-sandbox", "--hide-scrollbars", "--use-gl=angle", "--use-angle=swiftshader", "--enable-unsafe-swiftshader", "--ignore-gpu-blocklist"],
});
const page = await browser.newPage();
await page.setViewport({ width: 2400, height: 1350, deviceScaleFactor: 1 });
page.on("pageerror", (e) => console.log("  page error:", e.message));

const W = 2400, H = 1350;
for (const key of scenes) {
  const t0 = Date.now();
  await page.goto(`${html}?module=${key}&mode=hero`, { waitUntil: "load", timeout: 180_000 });
  await page.waitForFunction(() => window.__done === true, { timeout: 180_000 });
  const anchors = await page.evaluate(() => window.__anchors);
  const canvas = await page.$("canvas");
  const png = await canvas.screenshot({ type: "png", omitBackground: true });
  // Trim transparent margins; the trim offsets re-base the anchors.
  const trimmed = await sharp(png).trim({ threshold: 8 }).png().toBuffer({ resolveWithObject: true });
  const { width, height, trimOffsetLeft = 0, trimOffsetTop = 0 } = trimmed.info;
  const ox = -trimOffsetLeft, oy = -trimOffsetTop;
  const norm = ([x, y]) => [+(((x - ox) / width)).toFixed(4), +(((y - oy) / height)).toFixed(4)];
  const file = `${outDir}/${key}.webp`;
  await sharp(trimmed.data).webp({ quality: 86, alphaQuality: 90, effort: 5 }).toFile(file);
  const small = `${outDir}/${key}-800.webp`;
  await sharp(trimmed.data).resize({ width: 800 }).webp({ quality: 82, alphaQuality: 90 }).toFile(small);
  existing[key] = {
    src: `/${file.replace(/^public\//, "")}`,
    src800: `/${small.replace(/^public\//, "")}`,
    width, height,
    title: anchors.title, tagline: anchors.tagline,
    cableTargets: anchors.cableTargets.map(norm),
    groups: anchors.groups.map((g) => ({ label: g.label, at: norm(g.at) })),
    tag: norm(anchors.tag),
    panelTop: norm(anchors.panelTop),
  };
  const size = fs.statSync(file).size;
  console.log(`${key.padEnd(22)} ${width}x${height}  ${Math.round(size / 1024)}KB  (${((Date.now() - t0) / 1000).toFixed(1)}s)`);
}
await browser.close();

const body = JSON.stringify(existing, null, 2);
fs.writeFileSync(genPath, `/* Generated by scripts/render-scene.mjs — do not edit by hand. */\n// prettier-ignore\nexport const scenes = ${body} as const;\n\nexport type SceneKey = keyof typeof scenes;\n`);
console.log(`wrote ${genPath} (${Object.keys(existing).length} scenes)`);
