/** The coded pages an editor can take over in the builder (the catalog's detail pages stay generated). */
export const SITE_ROUTES: { path: string; title: string }[] = [
  { path: "/", title: "Home" },
  { path: "/platform", title: "Platform overview" },
  { path: "/products", title: "Products" },
  { path: "/editions", title: "Editions" },
  { path: "/modules", title: "Modules" },
  { path: "/products/whale-ai", title: "Whale AI" },
  { path: "/products/whaleforge", title: "WhaleForge" },
  { path: "/fabric", title: "BlueWhale Stack Fabric" },
  { path: "/pricing", title: "Pricing" },
  { path: "/solutions", title: "Solutions" },
  { path: "/industries", title: "Industries" },
  { path: "/customers", title: "Customer success stories" },
  { path: "/case-studies", title: "Case studies" },
  { path: "/resources", title: "Resources" },
  { path: "/docs", title: "Documentation" },
  { path: "/trust", title: "Trust Center" },
  { path: "/about", title: "About" },
  { path: "/about/leadership", title: "Leadership & team" },
  { path: "/partners", title: "Partners" },
  { path: "/careers", title: "Careers" },
  { path: "/newsroom", title: "Newsroom" },
  { path: "/contact", title: "Contact" },
];
