/**
 * The hero copy of every page as the page code renders it — the fallback the
 * seed script loads into the "Page hero" documents and the starting point when
 * a page is taken over in the website builder.
 */
import { portfolio } from "@/content/home";

/** The page heroes as they are written in the page code today. */
export const PAGE_HEROES: Record<string, { pageName: string; eyebrow: string; title: string; titleAccent?: string; description: string }> = {
  "/platform": { pageName: "Platform overview", eyebrow: "Digital Experience Multi-Cloud Platform — Cloud & Datacenter", title: "One Platform.", titleAccent: "Every Industry. Every Estate.", description: "BlueWhale Stack is one control plane over six public clouds, your virtualization estate and your air-gapped sites. It is run by enterprises, by telco and datacenter operators who sell governed services on it, and by governments that must prove where data lives and who touched it. After connecting, every estate reports into one inventory, one identity fabric and one policy engine — and the audit evidence is generated continuously instead of assembled per inspection." },
  "/modules": { pageName: "Modules", eyebrow: "The nine capability families", title: "What lives in the", titleAccent: "platform core.", description: "Fourteen modules across nine families, gated per edition — each with its own page showing what it does, how it works, the console screen, where it fits and the questions buyers ask. Maturity is stated on every card: GA, beta, preview or in progress." },
  "/editions": { pageName: "Editions", eyebrow: "Editions · four licences, one deployment", title: "Four editions.", titleAccent: "One architecture.", description: "Standard at $24,000 a year for a single AWS, Azure or GCP estate; Enterprise at $120,000 a year for every cloud and every estate; the Telco & Datacenter Edition for operators who sell governed cloud services; the Government Edition for air-gapped, accredited estates. An upgrade is a licence change, never a migration." },
  "/industries": { pageName: "Industries", eyebrow: "Industry solutions · eight sectors, one control plane", title: "Every sector, and the regimes each one answers to.", description: "Every industry page names the regulators and frameworks that sector actually faces — RBI and CERT-In, DPDP and GDPR, accreditation and air-gap mandates, carrier SLAs — and the platform control that answers each. Standard, Enterprise and Government editions are generally available today; the Telco & Datacenter Edition is in preview ahead of GA in Q4 2026." },
  "/solutions": { pageName: "Solutions", eyebrow: "Solutions · six outcomes, one control plane", title: "Six things teams buy the platform for.", description: "One inventory across every cloud, provisioning without console access, observability included in the licence, a scored migration plan, one identity fabric with continuous audit evidence, and a sovereign deployment that proves where data lives. Each solution page shows the data path, the console, the modules involved and a delivered engagement." },
  "/resources": { pageName: "Resources", eyebrow: "Resources", title: "Datasheets, briefs, whitepapers and case studies — read online or download.", description: "The documents a procurement or architecture review asks for: the official collateral kit as finished PDFs, plus a datasheet per edition, a brief per solution and per industry, four case studies and the company profile as reading pages. No form, no email required." },
  "/products": { pageName: "Products", eyebrow: "The product portfolio", title: "Four products.", titleAccent: "One platform DNA.", description: portfolio.description },
  "/trust": { pageName: "Trust Center", eyebrow: "Trust Center", title: "Security and compliance,", titleAccent: "independently verified.", description: "Five ISO management-system certifications — 27001, 27017, 27018, 27701 and 22301 — audited by accredited third-party bodies, plus a CSA STAR Level 1 self-assessment, a GDPR compliance assessment and a SOC 2 Type II readiness assessment. All current, with eight signed certificates downloadable below and full audit reports available to customers under NDA." },
  "/partners": { pageName: "Partners", eyebrow: "Partner Ecosystem", title: "Grow together.", titleAccent: "Win together.", description: "Three ways to partner with BlueWhale Stack — resell licences, implement and support the platform for end customers, or operate as the official partner for your country. Apply in minutes and go live after approval." },
  "/pricing": { pageName: "Pricing", eyebrow: "Pricing", title: "Two published prices. Two shaped to the estate.", description: "Standard is $24,000 a year and Enterprise is $120,000 a year — flat, published, on 1-, 3- or 5-year terms with 10% off for two years and 15% off for three. The Telco & Datacenter and Government editions are priced per operator or per contract, because they are metered on network elements, racks or sovereignty scope rather than on cloud accounts." },
  "/about": { pageName: "About", eyebrow: "About BlueWhale Stack", title: "A consulting firm that turned eight years of field work into a platform.", description: "BlueWhale Stack was founded in Mumbai in 2018 as a cloud consultancy. After eight years of migrations, audits and datacenter modernisations for telcos, banks, governments and hospitals in India and the GCC, the same gap kept appearing — no single view of the estate — and in 2026 we shipped the platform that closes it. Three entities today: the United States, the UAE and India." },
  "/careers": { pageName: "Careers", eyebrow: "Careers", title: "Build the control plane that banks, ministries and operators run on.", description: "We are engineers, architects and product people in Mumbai, Ajman and Wilmington, building one platform across six public clouds, virtualised estates and air-gapped sites. The work is concrete — connectors, discovery engines, policy evaluation, an AI layer that runs offline — and it ships quarterly to customers who audit what we build." },
  "/customers": { pageName: "Customer success stories", eyebrow: "Customer success stories · four delivered engagements", title: "Banks, ministries, operators and a newsroom — what changed for each.", description: "Banks under two regulators, defence ministries with air-gapped estates, telcos and datacenter operators becoming cloud providers, a global newsroom under sustained cyber threat. Client identities are withheld under confidentiality; the challenges, the solutions and the outcomes are as delivered." },
  "/case-studies": { pageName: "Case studies", eyebrow: "Case studies · situation, work, outcome", title: "Four estates, written up the way an architect reads them.", description: "Four delivered engagements, written up the way an architect or a CFO would want to read them — what the estate looked like, what BlueWhale Stack changed, and what the auditor, the board and the bill said afterwards." },
  "/fabric": { pageName: "BlueWhale Stack Fabric", eyebrow: "BlueWhale Stack Fabric · Strategic initiative · launching in India", title: "Every datacenter. One fabric.", description: "A market's datacenter capacity — every operator, every tier — unified on one platform and consumed by every kind of customer as a single sovereign cloud: one catalog, one identity, one bill. Public cloud stays at the edge; the fabric's core stays in-country. Delivered per market — launching in India, built for every country." },
  "/products/whale-ai": { pageName: "Whale AI", eyebrow: "Whale AI · Horizontal intelligence layer", title: "AI that answers from", titleAccent: "your live estate", description: "Whale AI is an intelligence layer inside every module of the platform. Each of its 50+ use cases declares the live data it reads — inventory, billing, tickets, findings — and cites it in the answer. It runs in three tiers by task complexity, on hosted models, your own model, or fully offline inside the perimeter for sovereign estates." },
  "/newsroom": { pageName: "Newsroom", eyebrow: "Newsroom", title: "Releases, certifications and milestones — dated.", description: "What shipped and when: edition general availability, new cloud connectors, module betas and the certification audits as they complete. For press enquiries, reach us at contact@bluewhalestack.com." },
};

